name: Buf CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buf-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          version: 1.50.0
          token: ${{ secrets.BUF_TOKEN}}
          lint: true
          format: true
          breaking: false
