---
name: 'OPI Inventory API CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'inventory/v1/**'
      - 'inventory/Makefile'
      - '.github/workflows/inventory.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'common/v1/**'
      - 'common/Makefile'
      - 'inventory/v1/**'
      - 'inventory/Makefile'
      - '.github/workflows/inventory.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: inventory-api-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-inventory-protobuf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@7703e82fbced3d0c9eec08dff4429c023a5fd9a9

    - name: Build protobufs
      run: make
      working-directory: inventory

    - name: Check uncomitted auto generated protobufs
      run: git diff --exit-code
      working-directory: inventory

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        path: inventory/v1/gen/go/*.pb.go
        retention-days: 1
