name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --ignore ./storage/proto/autogen.md --ignore ./security/proto/autogen.md --ignore ./network/proto/autogen.md --disable=MD013 "**/*.md"

  api-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install api-linter tool
        run: |
          go install github.com/googleapis/api-linter/cmd/api-linter@latest
      - name: Run linter
        run: |
          echo '::echo::on'
          $HOME/go/bin/api-linter **/proto/*.proto --output-format summary
          echo '::echo::off'

